pipeline{
   agent{
      node{
        label 'agent-1'
      }
   }

   environment{
    COURSE = "devops"
    app_version =""
    account_id = "349727115914"
    project ="roboshop"
    component = "catalogue"
   }

    stages{
        stage('terraform init'){
            steps{
                script{
                sh """
                cd  10-sg
                terraform init
                """

                } 
            }
        }

      
        stage('terraform plan'){
            steps{
                script{
                    sh """
                    cd  10-sg
                    terraform plan
                    """
                }
            }
        }

        stage('terraform build'){
            steps{
                script{
                    withAWS(credentials:'aws-cred') {
    // do something
}
                    sh """
                         cd 10-sg
                         terraform apply --auto-approve

                       """
                }
            }
        }

    
  
        stage('deploy'){
            steps{
                script{
                sh """
                echo "it is deply phase"
                """
            }
            }
        }
    }

    post{
        always{
                echo "workspace is clean"
                cleanWs()
            }
            success {
                echo "this is success"
            }
            failure{
                echo "this is failure"
            }
            aborted{
                echo "this is aborted"
            }
        }
    
}