pipeline{
   agent{
      node{
        label 'agent-1'
      }
   }

   environment{
    COURSE = "devops"
    app_version =""
    account_id = "349727115914"
    project ="roboshop"
    component = "catalogue"
   }

    stages{
        stage('terraform init'){
            steps{
                script{
                sh """
                cd  10-sg
                terraform init
                """

                } 
            }
        }

      
        stage('terraform plan'){
            steps{
                script{
                    sh """
                    cd  10-sg
                    terraform plan
                    """
                }
            }
        }

        stage('terraform build'){
            steps{
                script{
                    withAWS(credentials:'aws-cred') {
    // do something
}
                    sh """
                         cd 10-sg
                         terraform apply --auto-approve

                       """
                }
            }
        }

        stage(' Parallel trigger') {
            parallel {
                stage('bastion') {
                   steps {
                        script{
                        // Triggers 'Job-B', waits for it to finish, and propagates its status
                            build job: '20-bastion', propagate: false, wait: false
                        }
                    }
                    
                }
            }

        }
  
         stage('Parellel Trigger'){
            parallel {
                stage('Bastion'){
                    steps {
                        script {
                            build job: '20-bastion',
                                wait: false, // Wait for completion
                                propagate: false // Propagate status
                        }
                    }
                }
                stage('SG Rules'){
                    steps {
                        script {
                            build job: '30-sg-rules',
                                wait: false, // Wait for completion
                                propagate: false // Propagate status
                        }
                    }
                }
                stage('ECR'){
                    steps {
                        script {
                            build job: '40-ecr',
                                wait: false, // Wait for completion
                                propagate: false // Propagate status
                        }
                    }
                }
                stage('ACM'){
                    steps {
                        script {
                            build job: '70-acm',
                                wait: true, // Wait for completion
                                propagate: false // Propagate status
                        }
                    }
                }
                stage('EKS'){
                    steps {
                        script {
                            build job: '90-eks',
                                wait: false, // Wait for completion
                                propagate: false // Propagate status
                        }
                    }
                }
            }
        }
        stage('ALB'){
            steps {
                script {
                    build job: '80-frontend-alb',
                        wait: false, // Wait for completion
                        propagate: false // Propagate status
                }
            }
        }
    }

    post{
        always{
                echo "workspace is clean"
                cleanWs()
            }
            success {
                echo "this is success"
            }
            failure{
                echo "this is failure"
            }
            aborted{
                echo "this is aborted"
            }
        }
    
}